export const data = [
  {
    icon: "firstHalfIcon",
    imageSite: "left",
    id: 1,
    checksrc: "https://arenavs.com/check.png",
    unchecksrc: "https://arenavs.com/uncheck.png",
    animalUrl: "https://arenavs.com/bear.png",
    checkTexts: [
      "Lite Paper",
      "White Paper",
      "Smart Contract",
      "Contract Audit",
      "New HUD",
      "Seed Round",
    ],
    uncheckTexts: ["Private Round"],
  },
  {
    icon: "firstHalfIcon",
    id: 2,
    imageSite: "right",

    checksrc: "https://arenavs.com/check.png",
    unchecksrc: "https://arenavs.com/uncheck.png",
    animalUrl: "https://arenavs.com/fox.png",
    checkTexts: false,
    uncheckTexts: [
      "Public Sale",
      "Obtain Coingecko Listing",
      "Obtain Coinmarketcap Listing",
      "Centralized exchange Listing",
      "Game Launch On GameXChange",
      "Game Currency Integration",
    ],
  },
  {
    icon: "secodHalfIcon",
    id: 3,
    imageSite: "left",

    checksrc: "https://arenavs.com/check.png",
    unchecksrc: "https://arenavs.com/uncheck.png",
    animalUrl: "https://arenavs.com/wolf.png",
    checkTexts: false,
    uncheckTexts: [
      "NFT Marketplace and NFT Rewards",
      "NFT Pair Staking/Forming",
      "NFT Asset Games Integration",
      "Single Asset Staking",
      "Additional NFT Assets",
      "Additional Characters",
    ],
  },
  {
    icon: "secodHalfIcon",
    id: 4,
    imageSite: "right",
    checksrc: "https://arenavs.com/check.png",
    unchecksrc: "https://arenavs.com/uncheck.png",
    animalUrl: "https://arenavs.com/kib.png",
    checkTexts: false,
    uncheckTexts: [
      "Game rewards for game asset & NFT",
      "New NFT Collectibles",
      "Collaboration With Influencers",
      "User-Generated Events",
      "New Partnerships",
      "VR gallery",
      "Arena Mastser VR (Quest 2)",
    ],
  },
];
