export const tokeonmicsData = [
  {
    pool: "SEED",
    amtPrice: "$ 0,0883",
    raised: "$ 132,480",
    procent: "1.5",
    tokens: "1 500 000",
    active: false,

    // color: 'red
  },
  {
    pool: "Private Sale",
    amtPrice: "$ 0,1200",
    raised: "$ 600,000",
    procent: "5",
    tokens: "5 000 000",
    active: false,
    // color: "red",
  },
  {
    pool: "Public Sale",
    amtPrice: "$ 0,2000",
    raised: "$ 300,000",
    procent: "1.5",
    tokens: "1 500 000",
    active: false,
    // color: "red",
  },
  {
    pool: "Liquidity",
    amtPrice: "",
    raised: "",
    procent: "3",
    tokens: "3 000 000",
    active: false,
    // color: "red",
  },
  {
    pool: "Marketing",
    amtPrice: "",
    raised: "",
    procent: "5",
    tokens: "5 000 000",
    active: false,
    // color: "red",
  },
  {
    pool: "Development",
    amtPrice: "",
    raised: "",
    procent: "10",
    tokens: "10 000 000",
    active: false,
    // color: "red",
  },
  {
    pool: "Ecosystem Growth",
    amtPrice: "",
    raised: "",
    procent: "16",
    tokens: "16 000 000",
    active: false,

    // color: "red",
  },
  {
    pool: "Team",
    amtPrice: "",
    raised: "",
    procent: "10",
    tokens: "10 000 000",
    active: false,
    // color: "red",
  },
  {
    pool: "Advisor",
    amtPrice: "",
    raised: "",
    procent: "5",
    tokens: "5 000 000",
    active: false,
    // color: "red",
  },
  {
    pool: "Staking / Farming",
    amtPrice: "",
    raised: "",
    procent: "23",
    tokens: "23 000 000",
    active: false,

    // color: "red",
  },
  {
    pool: "Airdrop",
    amtPrice: "",
    raised: "",
    procent: "0.5",
    tokens: "500 000",
    active: false,
    // color: "red",
  },
  {
    pool: "Game Rewards",
    amtPrice: "",
    raised: "",
    procent: "19.5",
    tokens: "19 500 000",
    active: false,
    // color: "red",
  },
];
